-- 2022년 1월의 도서 판매 데이터를 기준으로 
-- 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 
-- 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 출력

WITH BOOK_INFO AS (
    SELECT
        A.BOOK_ID, A.CATEGORY, A.AUTHOR_ID, A.PRICE, A.PUBLISHED_DATE, B.AUTHOR_NAME -- 조인된 다음이니까 다 A인가? B.AUTHOR_NAME이 아니라?
    FROM 
        BOOK A
        JOIN AUTHOR B
        ON A.AUTHOR_ID = B.AUTHOR_ID
)

SELECT 
    A.AUTHOR_ID, A.AUTHOR_NAME, A.CATEGORY, SUM(B.SALES * A.PRICE) AS TOTAL_SALES
FROM
    BOOK_INFO A
    LEFT JOIN BOOK_SALES B
    ON A.BOOK_ID = B.BOOK_ID
WHERE 
    TO_CHAR(B.SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY 
    A.AUTHOR_ID, A.AUTHOR_NAME, A.CATEGORY
ORDER BY 
    A.AUTHOR_ID, A.CATEGORY DESC