-- 테이블이 3개. 책정보, 도서정보, 판매정보
SELECT A.AUTHOR_ID , B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK AS A
LEFT JOIN AUTHOR AS B
ON A.AUTHOR_ID = B.AUTHOR_ID
LEFT JOIN BOOK_SALES AS C
ON A.BOOK_ID = C.BOOK_ID
WHERE DATE_FORMAT(C.SALES_DATE,"%Y-%m")="2022-01"
GROUP BY A.AUTHOR_ID, A.CATEGORY    -- 이해안됨 : 저자 별, 카테고리 별 매출액이라니? 두개에 대한 그룹화면 그냥 순서대로 하면 되는건가?



ORDER BY A.AUTHOR_ID, A.CATEGORY DESC;