SELECT B.USER_ID, B.NICKNAME, CONCAT_WS(" ",B.CITY, B.STREET_ADDRESS1, B.STREET_ADDRESS2) AS 전체주소, 
CONCAT_WS("-",SUBSTRING(B.TLNO,1,3),SUBSTRING(B.TLNO,4,4),RIGHT(B.TLNO,4)) AS 전화번호
-- 전화번호의 경우 xxx-xxxx-xxxx 같은 형태로 하이픈 문자열(-)을 삽입하여 출력
FROM USED_GOODS_BOARD AS A
LEFT JOIN USED_GOODS_USER AS B
ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID
HAVING COUNT(A.WRITER_ID) >= 3
ORDER BY B.USER_ID DESC;


-- CONCAT_WS("-", SUBSTRING(U.TLNO, 1, 3), SUBSTR(U.TLNO, 4, 4), RIGHT(U.TLNO, 4)) AS "전화번호"