--  완료된 중고 거래의 총금액 이 70만 원 이상인 사람 -> 상태가 done인것들 먼저 선별하고, 유저별로 그룹화 해서 가격을 더하면 됨.
SELECT B.USER_ID, B.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
LEFT JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = "DONE"
GROUP BY B.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES
