WITH RENT AS (
  SELECT CAR_ID, TO_CHAR(START_DATE, 'MM') AS MONTH
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
  WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
),
VALID AS (
  SELECT CAR_ID FROM RENT GROUP BY CAR_ID HAVING COUNT(*) >= 5
)
SELECT TO_NUMBER(R.MONTH) AS MONTH, R.CAR_ID, COUNT(*) AS RECORDS
FROM RENT R
JOIN VALID V ON R.CAR_ID = V.CAR_ID
GROUP BY R.MONTH, R.CAR_ID
ORDER BY MONTH, R.CAR_ID DESC;
