SELECT TITLE, A.BOARD_ID, REPLY_ID, A.WRITER_ID, A.CONTENTS, DATE_FORMAT(A.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_REPLY AS A
LEFT JOIN USED_GOODS_BOARD AS B
ON A.BOARD_ID = B.BOARD_ID
WHERE B.CREATED_DATE BETWEEN "2022-10-01" AND "2022-10-31"
ORDER BY CREATED_DATE, TITLE

-- 테이블은 두개
-- 2022년 10월에 작성된 ..
-- 게시글 제목(1), 게시글 ID(1,2), 댓글 ID(2), 작성자 ID(1,2), 댓글 내용(2), 댓글 작성일(1,2)을 조회
-- 
# SELECT TITLE, BOARD.BOARD_ID, REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_REPLY AS REPLY
# LEFT JOIN USED_GOODS_BOARD AS BOARD
# ON REPLY.BOARD_ID=BOARD.BOARD_ID
# WHERE DATE_FORMAT(BOARD.CREATED_DATE, '%Y-%m') = '2022-10'
# ORDER BY REPLY.CREATED_DATE, TITLE