SELECT 
    A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 
    TO_CHAR(B.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B
ON A.BOARD_ID = B.BOARD_ID
WHERE
    EXTRACT(YEAR FROM A.CREATED_DATE) = 2022
    AND
    EXTRACT(MONTH FROM A.CREATED_DATE) = 10
ORDER BY
    B.CREATED_DATE,
    A.TITLE
    
    
-- 어디서부터 조인되었고 안되었는지 모르겠음. JOIN-ON 다음에는 A로 참조하면 조인된 테이블을 참조하는 것인가? SELECT는 그럼 조인 안된?
