-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R
ON B.BOARD_ID = R.BOARD_ID
WHERE TO_CHAR(B.CREATED_DATE,'YYYY-MM') = '2022-10'
ORDER BY R.CREATED_DATE, B.TITLE

-- WRITER_ID도 컬럼이름이 겹치는데 어떻게 구분해야할까?
-- TO_CHAR를 이용해서 DATE 타입을 변환해야하는 경우는, 
-- 단순 비교만 