-- 2022년 1월의 카테고리 별 도서 판매량을 합산
SELECT A.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK A
LEFT JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(B.SALES_DATE, "%Y-%m")="2022-01"
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY