WITH FILTER1 AS (
SELECT
    CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM
    FOOD_PRODUCT
WHERE
    CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY
    CATEGORY
)
    

SELECT
    A.CATEGORY, B.MAX_PRICE, A.PRODUCT_NAME
FROM
    FOOD_PRODUCT A
    JOIN FILTER1 B
    ON A.CATEGORY = B.CATEGORY
    AND A.PRICE = B.MAX_PRICE
ORDER BY
    B.MAX_PRICE DESC;